#!/usr/bin/env bash
echo "You have downloaded shoppe from the rewrite branch, which is now deprecated. Please use master, master-candidate or develop instead. We apologize for the inconvinience."
exit 1
