#!/usr/bin/env bash

# Packaging utilities for shoppe

# operations:

# arch2shoppe
# alpine2shoppe

[[ -z "$*" ]] && {
	echo "No operation specified!"
	exit 1
}

arch2shoppe() {
	[[ -z "$1" ]] && {
		echo "No file provided!"
		exit 2
	}
	[[ ! -e "$1" ]] && {
		echo "File doesn't exist!"
		exit 2
	}
	[[ -z "$2" ]] && {
		echo "No output file specified!"
	}
	source $1
	echo -e "name='$pkgname'\n\
desc='$pkgdesc'\n\
version='$pkgver'\n\
revision='1'\n\
license='$license'
depends='$depends'\n\
makedepends='$makedepends'" > $2
	
}

case $1 in
	arch2shoppe) arch2shoppe $2 $3;;
#	alpine2shoppe) alpinetoshoppe $2 $3;;
esac
